spring.application.name=ticket-service

logging.level.liquibase=DEBUG
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ticket_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:ticket_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:ticket_pass}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Event service
clients.event-service.url=${EVENT_SERVICE_URL:http://localhost:8082}

# Kafka
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

app.kafka.notification-topic=notification.events
