server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5433/ticket_db
clients.event-service.url=http://localhost:8082
spring.kafka.bootstrap-servers=localhost:9092

logging.level.com.erdos.ticketapp=DEBUG
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health,info,conditions,loggers,liquibase,mappings
